In [8]:
    import pandas as pd
    df = pd.read_csv('dataset.csv')
    df = df.drop(columns=['description'])
    df.head()

  authors  ...  weight
0     [1]  ...  184.00
1     [2]  ...  367.00
2  [3, 4]  ...  220.00
3     [5]  ...  771.11
4     [6]  ...  130.00

[5 rows x 24 columns]

In [15]:
    category = pd.get_dummies(df.lang)
    df_baru = pd.concat([df, category], axis=1)
    df_baru = df_baru.drop(columns='lang')
    df_baru

              authors bestsellers-rank  ... zh  zxx
0                 [1]              NaN  ...  0    0
1                 [2]            67532  ...  0    0
2              [3, 4]           150327  ...  0    0
3                 [5]            85902  ...  0    0
4                 [6]            54186  ...  0    0
...               ...              ...  ... ..  ...
56004         [50461]            91560  ...  0    0
56005         [50460]           293917  ...  0    0
56006         [50462]              NaN  ...  0    0
56007  [50463, 50464]          104,945  ...  0    0
56008         [12018]          1188469  ...  0    0

[56009 rows x 104 columns]

In [26]:
    category = df_baru['categories'].values
    label = df_baru[['en', 'fr', 'es', 'de', 'pl']].values

In [28]:
    from sklearn.model_selection import train_test_split
    category_latih, category_test, label_latih, label_test = train_test_split(category, label, test_size=0.2)

In [30]:
    from tensorflow.keras.preprocessing.text import Tokenizer
    from tensorflow.keras.preprocessing.sequence import pad_sequences
     
    tokenizer = Tokenizer(num_words=5000, oov_token='x')
    tokenizer.fit_on_texts(category_latih) 
    tokenizer.fit_on_texts(category_test)
     
    sekuens_latih = tokenizer.texts_to_sequences(category_latih)
    sekuens_test = tokenizer.texts_to_sequences(category_test)
     
    padded_latih = pad_sequences(sekuens_latih) 
    padded_test = pad_sequences(sekuens_test)

In [31]:
    import tensorflow as tf
    model = tf.keras.Sequential([
        tf.keras.layers.Embedding(input_dim=5000, output_dim=16),
        tf.keras.layers.LSTM(64),
        tf.keras.layers.Dense(128, activation='relu'),
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dense(5, activation='softmax')
    ])
    model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [32]:
    num_epochs = 30
    history = model.fit(padded_latih, label_latih, epochs=num_epochs, 
                        validation_data=(padded_test, label_test), verbose=2)

Epoch 1/30
1401/1401 - 29s - loss: 9.8709 - accuracy: 0.8745 - val_loss: 59.9018 - val_accuracy: 0.0201
Epoch 2/30
1401/1401 - 29s - loss: 60.8364 - accuracy: 0.8570 - val_loss: 106.9129 - val_accuracy: 0.9455
Epoch 3/30
1401/1401 - 30s - loss: 145.2841 - accuracy: 0.8568 - val_loss: 151.0905 - val_accuracy: 0.9455
Epoch 4/30
1401/1401 - 30s - loss: 274.2259 - accuracy: 0.8581 - val_loss: 332.5632 - val_accuracy: 0.0201
Epoch 5/30
1401/1401 - 30s - loss: 428.9695 - accuracy: 0.8576 - val_loss: 330.7008 - val_accuracy: 0.9455
Epoch 6/30
1401/1401 - 30s - loss: 608.3052 - accuracy: 0.8568 - val_loss: 784.8190 - val_accuracy: 0.9455
Epoch 7/30
1401/1401 - 30s - loss: 835.2051 - accuracy: 0.8571 - val_loss: 1462.5059 - val_accuracy: 0.9455
Epoch 8/30
1401/1401 - 30s - loss: 1066.0154 - accuracy: 0.8569 - val_loss: 606.1138 - val_accuracy: 0.9455
Epoch 9/30
1401/1401 - 31s - loss: 1371.9165 - accuracy: 0.8568 - val_loss: 1472.4016 - val_accuracy: 0.9455
Epoch 10/30
1401/1401 - 30s - loss: 1613.5219 - accuracy: 0.8565 - val_loss: 1848.6078 - val_accuracy: 0.9455
Epoch 11/30
1401/1401 - 31s - loss: 2008.6122 - accuracy: 0.8567 - val_loss: 1728.5713 - val_accuracy: 0.9455
Epoch 12/30
1401/1401 - 30s - loss: 2366.7065 - accuracy: 0.8565 - val_loss: 3880.2407 - val_accuracy: 0.9455
Epoch 13/30
1401/1401 - 29s - loss: 2776.6316 - accuracy: 0.8569 - val_loss: 3883.4304 - val_accuracy: 0.9455
Epoch 14/30
1401/1401 - 30s - loss: 3290.5269 - accuracy: 0.8565 - val_loss: 2606.9404 - val_accuracy: 0.9455
Epoch 15/30
1401/1401 - 30s - loss: 3573.2788 - accuracy: 0.8580 - val_loss: 2278.9026 - val_accuracy: 0.9455
Epoch 16/30
1401/1401 - 30s - loss: 4125.8931 - accuracy: 0.8561 - val_loss: 6198.5918 - val_accuracy: 0.9455
Epoch 17/30
1401/1401 - 29s - loss: 4684.9473 - accuracy: 0.8568 - val_loss: 3508.0342 - val_accuracy: 0.9455
Epoch 18/30
1401/1401 - 29s - loss: 5487.6787 - accuracy: 0.8555 - val_loss: 8051.8193 - val_accuracy: 0.9455
Epoch 19/30
1401/1401 - 30s - loss: 6120.1445 - accuracy: 0.8573 - val_loss: 4887.8545 - val_accuracy: 0.9455
Epoch 20/30
1401/1401 - 30s - loss: 6328.6763 - accuracy: 0.8561 - val_loss: 9056.3633 - val_accuracy: 0.9455
Epoch 21/30
1401/1401 - 29s - loss: 7248.8081 - accuracy: 0.8572 - val_loss: 10224.2959 - val_accuracy: 0.0095
Epoch 22/30
1401/1401 - 30s - loss: 7688.1528 - accuracy: 0.8569 - val_loss: 7568.5439 - val_accuracy: 0.9455
Epoch 23/30
1401/1401 - 29s - loss: 8506.9072 - accuracy: 0.8573 - val_loss: 5703.1528 - val_accuracy: 0.9455
Epoch 24/30
1401/1401 - 30s - loss: 9265.2891 - accuracy: 0.8563 - val_loss: 16421.4688 - val_accuracy: 0.9455
Epoch 25/30
1401/1401 - 29s - loss: 10370.8604 - accuracy: 0.8566 - val_loss: 17554.9160 - val_accuracy: 0.9455
Epoch 26/30
1401/1401 - 29s - loss: 11203.6465 - accuracy: 0.8564 - val_loss: 8895.2891 - val_accuracy: 0.9455
Epoch 27/30
1401/1401 - 30s - loss: 11967.6104 - accuracy: 0.8569 - val_loss: 11088.7002 - val_accuracy: 0.9455
Epoch 28/30
1401/1401 - 30s - loss: 12411.8721 - accuracy: 0.8571 - val_loss: 8246.9385 - val_accuracy: 0.9455
Epoch 29/30
1401/1401 - 30s - loss: 13518.7266 - accuracy: 0.8565 - val_loss: 13927.6846 - val_accuracy: 0.9455
Epoch 30/30
1401/1401 - 29s - loss: 14511.2959 - accuracy: 0.8564 - val_loss: 21866.3184 - val_accuracy: 0.9455